### ISSUE TITLE
Improve ServoStats.js

### ISSUE THREAD

**Issue by sole** [mozdevs/servo-experiments#17]
Jack suggests maybe using the method they use in https://www.servoexperiments.com/physics/125.html which uses a counter for the FPS

**Comment by metajack** [comment]
It would also be nice specifically for dogemania if there was a graph in a corner alongside or opposite of the counter. Something like this ![](http://i.imgur.com/HctKWMI.jpg)

**Comment by samuknet** [comment]
https://github.com/mozdevs/servo-experiments/commit/e8d6ad0df85eb26ec2cc341911c59a07dd34d3ce

Graph issue in #18

**Comment by samuknet** [comment]
@metajack Added FPS graph to [DogeMania](https://mozdevs.github.io/servo-experiments/experiments/dogemania/). Still needs a little work though.
