### ISSUE TITLE
Simplify the root directory

### ISSUE THREAD

**Issue by sole** [mozdevs/servo-experiments#25]
Right now there are images (e.g. indexScreenshot.png, servo.png) and json files and js and all sorts of stuff in the root directory. This is a bit overwhelming if you're new to a repository, so I'd suggest that images be moved to their own folder, .js files to the .js folders and probably the .json file can stay there.

**Comment by samuknet** [comment]
https://github.com/mozdevs/servo-experiments/commit/60c69c710dd6c80beaf3fedd531b0f2ac348b802

**Comment by sole** [comment]
Don't be so fast, images might be broken ;) (e.g. README and probably some experiments maybe too?)

**Comment by sole** [comment]
Don't be so fast, images might be broken ;) (e.g. README and probably some experiments maybe too?)
