### ISSUE TITLE
Bookshelf Demo

### ISSUE THREAD

**Issue by samuknet** [mozdevs/servo-experiments#6]
@sole :
Create a demo of a virtual 'bookshelf' where the different 'spines of books' are vertical tabs, which display clearly the name of the related content.

When clicked, they expand horizontally to reveal the underlying 'book' content to be displayed.

Initially the 'book content' is just going to be Wikipedia IFrames.  For a (v. near) future iteration, there is scope to extend this to actual HTML rendered books using the material at [http://gutenberg.org/](http://gutenberg.org/).

The demo should look visually appealing and run smoothly in Servo.  @sole Recommends to pick colours from [http://www.colourlovers.com/](http://www.colourlovers.com/).

**Comment by sole** [comment]
Things to do to complete it
- [x] use an anchor + hash link to start displaying the cover page of each book - **on hold: it seems in page anchors are not working** [https://github.com/servo/servo/issues/12587](https://github.com/servo/servo/issues/12587) -This has been worked around by moving ebook "preamble" to the end, so the html book starts on the cover page.
- [x] Related bug fixed https://github.com/servo/servo/issues/12554
- [x] styling so it looks nicer and not "Times new roman" style
- [x] look at text encoding to prevent rhomboids of death - **RIP Rhomboids**
- [x] figure out how to test in Android device
- [x] collect the most terrible bugs and try to make them high priority
- [x] Add author at bottom of book spine
- [x] Project Gutenberg credit
- [ ] Fix issue where IFrames width expand slower than their container (IIRC this doesn't occur when running with browser.html)
- [ ] Work  on 'heavy-book' branch which makes book html IFrames more demanding to resize (so it is as difficult as the wikipedia pages)

**Comment by samuknet** [comment]
@sole should I close this now? I can file the various minor issues it has separately
